Update build_and_push_docker_image.yml

diff --git a/.github/workflows/build_and_push_docker_image.yml b/.github/workflows/build_and_push_docker_image.yml
--- a/.github/workflows/build_and_push_docker_image.yml
+++ b/.github/workflows/build_and_push_docker_image.yml
@@ -66,6 +66,8 @@ jobs:
           
           docker buildx build \
             --platform ${{ matrix.platform }} \
+            --provenance=false \
+            --sbom=false \
             -t "${IMAGE}:${{ github.sha }}-${{ matrix.arch }}" \
             -t "${IMAGE}:${{ github.event.release.tag_name }}-${{ matrix.arch }}" \
             --push \
@@ -74,60 +76,60 @@ jobs:
     outputs:
       matrix: ${{ needs.define-matrix.outputs.matrix }}
       
-  # create-manifest:
-  #   needs: [build-and-push]
-  #   runs-on: ubuntu-22.04
-  #   steps:
-  #     - name: Docker login
-  #       uses: docker/login-action@v3
-  #       with:
-  #         registry: ghcr.io
-  #         username: ${{ github.actor }}
-  #         password: ${{ secrets.GITHUB_TOKEN }}
+  create-manifest:
+    needs: [build-and-push]
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Docker login
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
           
-  #     - name: 'Create Multi-Arch Manifest'
-  #       run: |
-  #         IMAGE=ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/${IMAGE_NAME}
+      - name: 'Create Multi-Arch Manifest'
+        run: |
+          IMAGE=ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/${IMAGE_NAME}
           
-  #         MATRIX_JSON='${{ needs.build-and-push.outputs.matrix }}'
+          MATRIX_JSON='${{ needs.build-and-push.outputs.matrix }}'
 
-  #         ARCHS=($(echo "$MATRIX_JSON" | jq -r '.[].arch'))
+          ARCHS=($(echo "$MATRIX_JSON" | jq -r '.[].arch'))
           
-  #         image_list=""
-  #         for arch in "${ARCHS[@]}"; do
-  #           image_list="$image_list $IMAGE:${{ github.event.release.tag_name }}-$arch"
-  #         done
-  #         image_list=$(echo $image_list | xargs)
+          image_list=""
+          for arch in "${ARCHS[@]}"; do
+            image_list="$image_list $IMAGE:${{ github.event.release.tag_name }}-$arch"
+          done
+          image_list=$(echo $image_list | xargs)
 
-  #         echo "\"$image_list\""
+          echo "\"$image_list\""
           
-  #         docker buildx imagetools create -t $IMAGE:${{ github.event.release.tag_name }} $image_list
-  #         docker buildx imagetools create -t $IMAGE:latest $image_list
+          docker buildx imagetools create -t $IMAGE:${{ github.event.release.tag_name }} $image_list
+          docker buildx imagetools create -t $IMAGE:latest $image_list
     
-  #   outputs:
-  #     matrix: ${{ needs.build-and-push.outputs.matrix }}
+    outputs:
+      matrix: ${{ needs.build-and-push.outputs.matrix }}
       
-  # verify-manifest:
-  #   name: 'Verify Manifest'
-  #   runs-on: ubuntu-latest
-  #   needs: [create-manifest]
+  verify-manifest:
+    name: 'Verify Manifest'
+    runs-on: ubuntu-latest
+    needs: [create-manifest]
 
-  #   steps:
-  #     - name: 'Verify'
-  #       run: |
-  #         MATRIX_JSON='${{ needs.create-manifest.outputs.matrix }}'
+    steps:
+      - name: 'Verify'
+        run: |
+          MATRIX_JSON='${{ needs.create-manifest.outputs.matrix }}'
           
-  #         ARCHS=($(echo "$MATRIX_JSON" | jq -r '.[].arch'))
-  #         IMAGE=ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/${IMAGE_NAME}:latest
-  #         OUTPUT=$(docker buildx imagetools inspect $IMAGE)
+          ARCHS=($(echo "$MATRIX_JSON" | jq -r '.[].arch'))
+          IMAGE=ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/${IMAGE_NAME}:latest
+          OUTPUT=$(docker buildx imagetools inspect $IMAGE)
           
-  #         echo "$OUTPUT"
+          echo "$OUTPUT"
           
-  #         for arch in "${ARCHS[@]}"; do
-  #           if ! echo "$OUTPUT" | grep -q "$arch"; then
-  #             echo -e "\x1b[1;31mPlatform $arch is missing in manifest."
-  #             exit 1
-  #           fi
-  #         done
+          for arch in "${ARCHS[@]}"; do
+            if ! echo "$OUTPUT" | grep -q "$arch"; then
+              echo -e "\x1b[1;31mPlatform $arch is missing in manifest."
+              exit 1
+            fi
+          done
           
-  #         echo -e "\x1b[1;32mAll expected platforms found in manifest."
+          echo -e "\x1b[1;32mAll expected platforms found in manifest."
